// Additional dairy products
const additionalDairy = [
  {
    _id: '51',
    name: 'Organic Butter',
    slug: 'organic-butter',
    description: 'Creamy organic butter. Made from grass-fed cow milk.',
    price: 374,
    discountPrice: 0,
    stock: 40,
    countInStock: 40,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1589985270958-bf087de36e9e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Dairy Delight',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 15,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '52',
    name: 'Fresh Mozzarella',
    slug: 'fresh-mozzarella',
    description: 'Creamy and soft fresh mozzarella. Perfect for salads and pizzas.',
    price: 299,
    discountPrice: 249,
    stock: 35,
    countInStock: 35,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1588010254198-7339543c9a56?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Cheese Masters',
    rating: 4.8,
    averageRating: 4.8,
    numReviews: 20,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '53',
    name: 'Low-Fat Yogurt',
    slug: 'low-fat-yogurt',
    description: 'Creamy low-fat yogurt. Rich in probiotics for gut health.',
    price: 249,
    discountPrice: 0,
    stock: 50,
    countInStock: 50,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Dairy Delight',
    rating: 4.4,
    averageRating: 4.4,
    numReviews: 12,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '54',
    name: 'Gouda Cheese',
    slug: 'gouda-cheese',
    description: 'Smooth and slightly sweet Gouda cheese. Perfect for sandwiches and cheese boards.',
    price: 399,
    discountPrice: 349,
    stock: 30,
    countInStock: 30,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1624806992066-5fff633b0513?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Cheese Masters',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 18,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '55',
    name: 'Heavy Cream',
    slug: 'heavy-cream',
    description: 'Rich and thick heavy cream. Perfect for cooking and baking.',
    price: 329,
    discountPrice: 0,
    stock: 45,
    countInStock: 45,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1570275239925-4af0aa11e4d6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Happy Cows',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 14,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '56',
    name: 'Cottage Cheese',
    slug: 'cottage-cheese',
    description: 'Fresh and mild cottage cheese. High in protein and versatile.',
    price: 274,
    discountPrice: 249,
    stock: 40,
    countInStock: 40,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1568814831358-c6e7d5f351ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Dairy Delight',
    rating: 4.3,
    averageRating: 4.3,
    numReviews: 11,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '57',
    name: 'Parmesan Cheese',
    slug: 'parmesan-cheese',
    description: 'Aged Parmesan cheese with rich nutty flavor. Perfect for grating over pasta.',
    price: 449,
    discountPrice: 399,
    stock: 25,
    countInStock: 25,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1528747045269-390fe33c19f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Cheese Masters',
    rating: 4.9,
    averageRating: 4.9,
    numReviews: 22,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '58',
    name: 'Sour Cream',
    slug: 'sour-cream',
    description: 'Tangy and rich sour cream. Perfect for topping and cooking.',
    price: 299,
    discountPrice: 0,
    stock: 35,
    countInStock: 35,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1568717929068-c8e9b22e3606?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Happy Cows',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 13,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '59',
    name: 'Blue Cheese',
    slug: 'blue-cheese',
    description: 'Bold and creamy blue cheese. Perfect for salads and cheese boards.',
    price: 474,
    discountPrice: 424,
    stock: 20,
    countInStock: 20,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1621089568200-a2a46a858742?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Cheese Masters',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 15,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '60',
    name: 'Skim Milk',
    slug: 'skim-milk',
    description: 'Low-fat skim milk. Great for those watching their fat intake.',
    price: 249,
    discountPrice: 224,
    stock: 50,
    countInStock: 50,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Happy Cows',
    rating: 4.3,
    averageRating: 4.3,
    numReviews: 10,
    isFeatured: false,
    reviews: []
  }
];

export default additionalDairy; 