// Additional fruit products
const additionalFruits = [
  {
    _id: '13',
    name: 'Organic Oranges',
    slug: 'organic-oranges',
    description: 'Sweet and juicy organic oranges. Rich in vitamin C and antioxidants.',
    price: 374,
    discountPrice: 299,
    stock: 35,
    countInStock: 35,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab12?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Citrus Valley',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 17,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '14',
    name: 'Ripe Mangoes',
    slug: 'ripe-mangoes',
    description: 'Sweet and tropical mangoes. Perfect for smoothies or desserts.',
    price: 524,
    discountPrice: 412,
    stock: 28,
    countInStock: 28,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Tropical Farms',
    rating: 4.9,
    averageRating: 4.9,
    numReviews: 23,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '15',
    name: 'Fresh Blueberries',
    slug: 'fresh-blueberries',
    description: 'Antioxidant-rich blueberries. Sweet and nutritious.',
    price: 449,
    discountPrice: 0,
    stock: 25,
    countInStock: 25,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Berry Good',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 19,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '16',
    name: 'Fresh Pineapple',
    slug: 'fresh-pineapple',
    description: 'Sweet and tropical pineapple. Ready to eat.',
    price: 374,
    discountPrice: 299,
    stock: 22,
    countInStock: 22,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Tropical Delights',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 15,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '17',
    name: 'Organic Grapes',
    slug: 'organic-grapes',
    description: 'Sweet and juicy organic grapes. Perfect for snacking.',
    price: 412,
    discountPrice: 0,
    stock: 30,
    countInStock: 30,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Vineyard Fresh',
    rating: 4.4,
    averageRating: 4.4,
    numReviews: 12,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '18',
    name: 'Fresh Watermelon',
    slug: 'fresh-watermelon',
    description: 'Sweet and refreshing watermelon. Perfect for summer days.',
    price: 524,
    discountPrice: 449,
    stock: 20,
    countInStock: 20,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1563114773-84221bd62daa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Summer Harvest',
    rating: 4.8,
    averageRating: 4.8,
    numReviews: 21,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '19',
    name: 'Fresh Kiwi',
    slug: 'fresh-kiwi',
    description: 'Tangy and sweet kiwi fruit. Rich in vitamin C and fiber.',
    price: 337,
    discountPrice: 0,
    stock: 32,
    countInStock: 32,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1618897996318-5a901fa6ca71?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Exotic Fruits',
    rating: 4.3,
    averageRating: 4.3,
    numReviews: 10,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '20',
    name: 'Organic Peaches',
    slug: 'organic-peaches',
    description: 'Sweet and juicy organic peaches.',
    price: 449,
    discountPrice: 374,
    stock: 25,
    countInStock: 25,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1639588473831-dd9d014646ae?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Orchard Fresh',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 16,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '21',
    name: 'Fresh Cherries',
    slug: 'fresh-cherries',
    description: 'Sweet and plump cherries.',
    price: 599,
    discountPrice: 0,
    stock: 20,
    countInStock: 20,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1611096265583-5d745a5f2bd2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Cherry Valley',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 18,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '22',
    name: 'Fresh Pears',
    slug: 'fresh-pears',
    description: 'Sweet and juicy pears.',
    price: 337,
    discountPrice: 299,
    stock: 35,
    countInStock: 35,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1631160299919-6a175aa6d189?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Orchard Fresh',
    rating: 4.2,
    averageRating: 4.2,
    numReviews: 9,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '23',
    name: 'Fresh Plums',
    slug: 'fresh-plums',
    description: 'Sweet and juicy plums. Perfect for snacking, baking, or making preserves.',
    price: 322,
    discountPrice: 0,
    stock: 30,
    countInStock: 30,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1603408209093-cd3c9af497d6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Stone Fruit Farms',
    rating: 4.4,
    averageRating: 4.4,
    numReviews: 11,
    isFeatured: false,
    reviews: [],
  },
  {
    _id: '24',
    name: 'Organic Lemons',
    slug: 'organic-lemons',
    description: 'Fresh organic lemons. Perfect for cooking, baking, or making refreshing lemonade.',
    price: 299,
    discountPrice: 224,
    stock: 40,
    countInStock: 40,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1590502593747-42a996133562?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Citrus Valley',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 13,
    isFeatured: false,
    reviews: [],
  },
  {
    _id: '25',
    name: 'Fresh Limes',
    slug: 'fresh-limes',
    description: 'Zesty and fresh limes. Perfect for cooking, cocktails, or adding flavor to dishes.',
    price: 262,
    discountPrice: 0,
    stock: 35,
    countInStock: 35,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1622957461168-76648809c961?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Citrus Fresh',
    rating: 4.3,
    averageRating: 4.3,
    numReviews: 10,
    isFeatured: false,
    reviews: [],
  },
  {
    _id: '26',
    name: 'Fresh Raspberries',
    slug: 'fresh-raspberries',
    description: 'Sweet and tangy raspberries. Perfect for desserts, smoothies, or eating fresh.',
    price: 487,
    discountPrice: 412,
    stock: 20,
    countInStock: 20,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1577069861033-55d04cec4ef5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Berry Good',
    rating: 4.8,
    averageRating: 4.8,
    numReviews: 20,
    isFeatured: true,
    reviews: [],
  },
  {
    _id: '27',
    name: 'Fresh Blackberries',
    slug: 'fresh-blackberries',
    description: 'Juicy and sweet blackberries. Great for breakfast, desserts, or snacking.',
    price: 449,
    discountPrice: 0,
    stock: 20,
    countInStock: 20,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1615218370629-da07db3571cc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Berry Fresh',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 15,
    isFeatured: false,
    reviews: [],
  },
  {
    _id: '28',
    name: 'Fresh Apricots',
    slug: 'fresh-apricots',
    description: 'Sweet and tangy apricots. Great for snacking, baking, or making jams.',
    price: 374,
    discountPrice: 299,
    stock: 25,
    countInStock: 25,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1599943503164-2dcaab73121a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Stone Fruit Farms',
    rating: 4.4,
    averageRating: 4.4,
    numReviews: 12,
    isFeatured: false,
    reviews: [],
  },
  {
    _id: '29',
    name: 'Fresh Pomegranate',
    slug: 'fresh-pomegranate',
    description: 'Antioxidant-rich pomegranate. Sweet and tart, perfect for juicing or adding to salads.',
    price: 374,
    discountPrice: 0,
    stock: 20,
    countInStock: 20,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1541344999736-83eca272f6fc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Exotic Fruits',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 18,
    isFeatured: true,
    reviews: [],
  },
  {
    _id: '30',
    name: 'Fresh Cantaloupe',
    slug: 'fresh-cantaloupe',
    description: 'Sweet and fragrant cantaloupe. Perfect for breakfast, fruit salads, or as a refreshing snack.',
    price: 412,
    discountPrice: 337,
    stock: 15,
    countInStock: 15,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1571575173700-afb9492e6a50?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Melon Patch',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 14,
    isFeatured: false,
    reviews: [],
  },
  {
    _id: '31',
    name: 'Fresh Honeydew Melon',
    slug: 'fresh-honeydew-melon',
    description: 'Sweet and juicy honeydew melon. Perfect for fruit salads or enjoying on its own.',
    price: 449,
    discountPrice: 0,
    stock: 15,
    countInStock: 15,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1579702493440-8b1b56d47e39?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Melon Patch',
    rating: 4.3,
    averageRating: 4.3,
    numReviews: 11,
    isFeatured: false,
    reviews: [],
  },
  {
    _id: '32',
    name: 'Organic Grapefruit',
    slug: 'organic-grapefruit',
    description: 'Tangy and refreshing organic grapefruit. Great for breakfast or making fresh juice.',
    price: 337,
    discountPrice: 299,
    stock: 30,
    countInStock: 30,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1596273312170-8f231e21080b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Citrus Valley',
    rating: 4.4,
    averageRating: 4.4,
    numReviews: 13,
    isFeatured: false,
    reviews: [],
  },
  {
    _id: '33',
    name: 'Green Kiwi',
    slug: 'green-kiwi',
    description: 'Sweet and tangy green kiwi. Full of vitamin C and makes a perfect healthy snack.',
    price: 374,
    discountPrice: 0,
    stock: 35,
    countInStock: 35,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1542400935-70190c63c242?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Exotic Fruits',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 16,
    isFeatured: true,
    reviews: [],
  },
  {
    _id: '34',
    name: 'Dragon Fruit',
    slug: 'dragon-fruit',
    description: 'Exotic dragon fruit with a mild sweet flavor. Beautiful and nutritious addition to fruit salads.',
    price: 599,
    discountPrice: 524,
    stock: 15,
    countInStock: 15,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1527325678457-068eabd8e229?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Exotic Farms',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 19,
    isFeatured: true,
    reviews: [],
  },
  {
    _id: '35',
    name: 'Golden Pineapple',
    slug: 'golden-pineapple',
    description: 'Extra sweet golden pineapple. Perfectly ripe and ready to eat.',
    price: 449,
    discountPrice: 0,
    stock: 20,
    countInStock: 20,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1589820296156-2454bb8a6ad1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Tropical Delights',
    rating: 4.8,
    averageRating: 4.8,
    numReviews: 22,
    isFeatured: false,
    reviews: [],
  },
  {
    _id: '36',
    name: 'Yellow Passion Fruit',
    slug: 'yellow-passion-fruit',
    description: 'Tangy and aromatic passion fruit. Great for juices, desserts, or adding tropical flavor to dishes.',
    price: 487,
    discountPrice: 412,
    stock: 20,
    countInStock: 20,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1604495772376-9fbb3996c4f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Exotic Fruits',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 17,
    isFeatured: false,
    reviews: [],
  },
  {
    _id: '37',
    name: 'Fresh Figs',
    slug: 'fresh-figs',
    description: 'Sweet and delicate fresh figs. Perfect for cheese boards, desserts, or enjoying fresh.',
    price: 599,
    discountPrice: 0,
    stock: 15,
    countInStock: 15,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1597095166794-36513dad77ab?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Mediterranean Farms',
    rating: 4.9,
    averageRating: 4.9,
    numReviews: 21,
    isFeatured: true,
    reviews: [],
  },
  {
    _id: '38',
    name: 'Fresh Dates',
    slug: 'fresh-dates',
    description: 'Sweet and caramel-like fresh dates. A natural energy booster and healthy snack.',
    price: 524,
    discountPrice: 449,
    stock: 25,
    countInStock: 25,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1629226162857-8b53df66486a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Date Oasis',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 18,
    isFeatured: false,
    reviews: [],
  },
  {
    _id: '39',
    name: 'Cotton Candy Grapes',
    slug: 'cotton-candy-grapes',
    description: 'Uniquely sweet grapes that taste like cotton candy. A fun and healthy treat for kids and adults.',
    price: 674,
    discountPrice: 562,
    stock: 20,
    countInStock: 20,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1633380110125-f6e685676160?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Grapery',
    rating: 4.9,
    averageRating: 4.9,
    numReviews: 24,
    isFeatured: true,
    reviews: [],
  },
  {
    _id: '40',
    name: 'Star Fruit',
    slug: 'star-fruit',
    description: 'Crisp and mildly sweet star fruit. Creates beautiful star-shaped slices perfect for garnishing.',
    price: 449,
    discountPrice: 0,
    stock: 15,
    countInStock: 15,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1602488283247-29bf1f5b148a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Exotic Fruits',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 15,
    isFeatured: false,
    reviews: [],
  },
];

export default additionalFruits; 