// Additional vegetable products
const additionalVegetables = [
  {
    _id: '41',
    name: 'Organic Tomatoes',
    slug: 'organic-tomatoes',
    description: 'Ripe and juicy organic tomatoes. Perfect for salads and cooking.',
    price: 299,
    discountPrice: 229,
    stock: 40,
    countInStock: 40,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1561136594-7f68413baa99?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Garden Fresh',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 16,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '42',
    name: 'Red Onions',
    slug: 'red-onions',
    description: 'Flavorful red onions. Great for salads and garnishes.',
    price: 187,
    discountPrice: 0,
    stock: 42,
    countInStock: 42,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1618512496248-a3c4a5d7df60?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Farm Fresh',
    rating: 4.3,
    averageRating: 4.3,
    numReviews: 11,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '43',
    name: 'Sweet Potatoes',
    slug: 'sweet-potatoes',
    description: 'Nutritious sweet potatoes. Versatile for many recipes.',
    price: 262,
    discountPrice: 224,
    stock: 38,
    countInStock: 38,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1596090942968-243a914e5823?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Root Vegetables',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 14,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '44',
    name: 'Fresh Zucchini',
    slug: 'fresh-zucchini',
    description: 'Tender and mild zucchini. Great for grilling or stir-fries.',
    price: 224,
    discountPrice: 0,
    stock: 33,
    countInStock: 33,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1583687355032-89b902b7335f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Garden Fresh',
    rating: 4.4,
    averageRating: 4.4,
    numReviews: 12,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '45',
    name: 'Butternut Squash',
    slug: 'butternut-squash',
    description: 'Sweet and nutty butternut squash. Perfect for soups and roasting.',
    price: 299,
    discountPrice: 224,
    stock: 28,
    countInStock: 28,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1570586437263-ab629fccc818?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Farm Fresh',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 18,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '46',
    name: 'Fresh Cucumber',
    slug: 'fresh-cucumber',
    description: 'Crisp and refreshing cucumber. Perfect for salads and sandwiches.',
    price: 187,
    discountPrice: 0,
    stock: 45,
    countInStock: 45,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1567375698348-5d9d5ae99de0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Garden Fresh',
    rating: 4.2,
    averageRating: 4.2,
    numReviews: 10,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '47',
    name: 'Red Bell Peppers',
    slug: 'red-bell-peppers',
    description: 'Sweet and crunchy red bell peppers. Great for stir-fries, salads, or roasting.',
    price: 299,
    discountPrice: 224,
    stock: 30,
    countInStock: 30,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Fresh Fields',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 15,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '48',
    name: 'Fresh Asparagus',
    slug: 'fresh-asparagus',
    description: 'Tender asparagus spears. Perfect for grilling, roasting, or steaming.',
    price: 374,
    discountPrice: 0,
    stock: 25,
    countInStock: 25,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1445282768818-728615cc910a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Fresh Fields',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 13,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '49',
    name: 'Brussels Sprouts',
    slug: 'brussels-sprouts',
    description: 'Nutritious Brussels sprouts. Great roasted with olive oil.',
    price: 262,
    discountPrice: 224,
    stock: 35,
    countInStock: 35,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1614268303998-1777cacfddde?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Green Valley',
    rating: 4.2,
    averageRating: 4.2,
    numReviews: 9,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '50',
    name: 'Fresh Kale',
    slug: 'fresh-kale',
    description: 'Nutritious and tender kale leaves. Perfect for salads, smoothies, or cooking.',
    price: 247,
    discountPrice: 0,
    stock: 40,
    countInStock: 40,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1524179091875-bf99a9a6af57?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Green Fields',
    rating: 4.3,
    averageRating: 4.3,
    numReviews: 11,
    isFeatured: false,
    reviews: []
  }
];

export default additionalVegetables; 