// Last batch of vegetable products
const lastVegetables = [
  {
    _id: '83',
    name: 'Purple Cabbage',
    slug: 'purple-cabbage',
    description: 'Vibrant purple cabbage. Great for slaws, salads, or cooking.',
    price: 3.49,
    discountPrice: 2.99,
    stock: 35,
    countInStock: 35,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Farm Fresh',
    rating: 4.4,
    averageRating: 4.4,
    numReviews: 13,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '84',
    name: 'Fresh Turnips',
    slug: 'fresh-turnips',
    description: 'Crisp and slightly sweet turnips. Great for roasting or adding to soups.',
    price: 2.99,
    discountPrice: 0,
    stock: 40,
    countInStock: 40,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1611105637889-3afd7295bdbf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Root Vegetables',
    rating: 4.2,
    averageRating: 4.2,
    numReviews: 10,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '85',
    name: 'Green Onions',
    slug: 'green-onions',
    description: 'Fresh and flavorful green onions. Perfect for garnishing or adding to stir-fries.',
    price: 1.99,
    discountPrice: 0,
    stock: 50,
    countInStock: 50,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1580294647332-8a399cd9ed6c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Garden Fresh',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 15,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '86',
    name: 'Organic Beets',
    slug: 'organic-beets',
    description: 'Vibrant organic beets. Great for salads, roasting, or juicing.',
    price: 3.79,
    discountPrice: 2.99,
    stock: 32,
    countInStock: 32,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Organic Valley',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 16,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '87',
    name: 'Fresh Radishes',
    slug: 'fresh-radishes',
    description: 'Crisp and peppery radishes. Great for salads or snacking.',
    price: 2.49,
    discountPrice: 0,
    stock: 42,
    countInStock: 42,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1566383444833-43afb88e5dc9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Garden Fresh',
    rating: 4.3,
    averageRating: 4.3,
    numReviews: 12,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '88',
    name: 'Fresh Leeks',
    slug: 'fresh-leeks',
    description: 'Fresh and aromatic leeks. Perfect for soups, stews, or roasting.',
    price: 3.49,
    discountPrice: 2.99,
    stock: 35,
    countInStock: 35,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Farm Fresh',
    rating: 4.4,
    averageRating: 4.4,
    numReviews: 14,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '89',
    name: 'Organic Baby Carrots',
    slug: 'organic-baby-carrots',
    description: 'Sweet and tender organic baby carrots. Perfect for snacking or cooking.',
    price: 3.49,
    discountPrice: 0,
    stock: 40,
    countInStock: 40,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1447175008436-054170c2e979?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Organic Valley',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 18,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '90',
    name: 'Fresh Fennel',
    slug: 'fresh-fennel',
    description: 'Aromatic fennel with a mild licorice flavor. Great for salads or roasting.',
    price: 3.99,
    discountPrice: 0,
    stock: 30,
    countInStock: 30,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1627735055374-cd72dbabf815?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Garden Fresh',
    rating: 4.4,
    averageRating: 4.4,
    numReviews: 13,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '91',
    name: 'Organic Kale',
    slug: 'organic-kale',
    description: 'Nutrient-dense organic kale. Perfect for salads, smoothies, or cooking.',
    price: 3.79,
    discountPrice: 2.99,
    stock: 38,
    countInStock: 38,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1618307953241-162c7072e371?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Organic Valley',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 15,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '92',
    name: 'Fresh Rhubarb',
    slug: 'fresh-rhubarb',
    description: 'Tart and vibrant rhubarb. Perfect for pies, jams, or compotes.',
    price: 4.49,
    discountPrice: 3.99,
    stock: 25,
    countInStock: 25,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1622554956172-1a340e135daf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Farm Fresh',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 16,
    isFeatured: true,
    reviews: []
  }
];

export default lastVegetables; 