// Last batch of dairy products
const lastDairy = [
  {
    _id: '93',
    name: 'Feta Cheese',
    slug: 'feta-cheese',
    description: 'Tangy and crumbly feta cheese. Perfect for salads or Mediterranean dishes.',
    price: 5.99,
    discountPrice: 4.99,
    stock: 30,
    countInStock: 30,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1559561853-08451507cbe7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Cheese Masters',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 18,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '94',
    name: 'Cashew Milk',
    slug: 'cashew-milk',
    description: 'Creamy plant-based cashew milk. Delicious dairy alternative.',
    price: 4.79,
    discountPrice: 0,
    stock: 35,
    countInStock: 35,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1600718374662-0483d2b9da44?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Plant Milks',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 16,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '95',
    name: 'Brie Cheese',
    slug: 'brie-cheese',
    description: 'Creamy and rich Brie cheese. Perfect for cheese boards or baking.',
    price: 6.99,
    discountPrice: 5.99,
    stock: 25,
    countInStock: 25,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1626957341926-98752fc2ba47?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Cheese Masters',
    rating: 4.8,
    averageRating: 4.8,
    numReviews: 20,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '96',
    name: 'Sour Cream',
    slug: 'sour-cream',
    description: 'Rich and tangy sour cream. Perfect for topping or cooking.',
    price: 3.49,
    discountPrice: 2.99,
    stock: 38,
    countInStock: 38,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1637949385637-964c023769dd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Dairy Delight',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 15,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '97',
    name: 'Cream Cheese',
    slug: 'cream-cheese',
    description: 'Smooth and creamy cheese spread. Perfect for bagels or baking.',
    price: 3.99,
    discountPrice: 0,
    stock: 40,
    countInStock: 40,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1634487359989-3e90c9432133?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Cheese Masters',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 17,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '98',
    name: 'Heavy Cream',
    slug: 'heavy-cream',
    description: 'Rich and thick heavy cream. Perfect for whipping or cooking.',
    price: 4.79,
    discountPrice: 3.99,
    stock: 35,
    countInStock: 35,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Happy Cows',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 18,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '99',
    name: 'Pepper Jack Cheese',
    slug: 'pepper-jack-cheese',
    description: 'Spicy and flavorful Pepper Jack cheese. Great for sandwiches or melting.',
    price: 5.49,
    discountPrice: 0,
    stock: 32,
    countInStock: 32,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Cheese Masters',
    rating: 4.8,
    averageRating: 4.8,
    numReviews: 19,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '100',
    name: 'Rice Milk',
    slug: 'rice-milk',
    description: 'Light and refreshing rice milk. Gentle dairy alternative.',
    price: 3.99,
    discountPrice: 0,
    stock: 38,
    countInStock: 38,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Plant Milks',
    rating: 4.4,
    averageRating: 4.4,
    numReviews: 14,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '101',
    name: 'Provolone Cheese',
    slug: 'provolone-cheese',
    description: 'Semi-soft Italian provolone cheese. Perfect for sandwiches or cooking.',
    price: 5.29,
    discountPrice: 4.79,
    stock: 30,
    countInStock: 30,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1634487360040-e069e6f08f39?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Cheese Masters',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 16,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '102',
    name: 'Lactose-Free Milk',
    slug: 'lactose-free-milk',
    description: 'Creamy lactose-free milk. All the benefits of milk without lactose.',
    price: 4.49,
    discountPrice: 0,
    stock: 42,
    countInStock: 42,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Happy Cows',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 18,
    isFeatured: true,
    reviews: []
  }
];

export default lastDairy; 