// Last batch of fruit products
const lastFruits = [
  {
    _id: '73',
    name: 'Fresh Guava',
    slug: 'fresh-guava',
    description: 'Sweet and aromatic guava. Rich in vitamin C and antioxidants.',
    price: 5.49,
    discountPrice: 4.99,
    stock: 25,
    countInStock: 25,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1536511132770-e5058c7e8c46?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Tropical Farms',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 15,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '74',
    name: 'Honeycrisp Apples',
    slug: 'honeycrisp-apples',
    description: 'Sweet and crisp Honeycrisp apples. A perfect balance of sweetness and tartness.',
    price: 5.99,
    discountPrice: 0,
    stock: 35,
    countInStock: 35,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1606757389667-45c2b7a5b311?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Local Orchards',
    rating: 4.8,
    averageRating: 4.8,
    numReviews: 20,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '75',
    name: 'Fresh Cranberries',
    slug: 'fresh-cranberries',
    description: 'Tart and nutritious cranberries. Perfect for sauces, baking, or juicing.',
    price: 4.99,
    discountPrice: 3.99,
    stock: 28,
    countInStock: 28,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1543158181-e6f9f6712055?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Berry Farms',
    rating: 4.4,
    averageRating: 4.4,
    numReviews: 12,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '76',
    name: 'Fresh Persimmons',
    slug: 'fresh-persimmons',
    description: 'Sweet and honeyed persimmons. A delicious seasonal treat.',
    price: 6.49,
    discountPrice: 0,
    stock: 20,
    countInStock: 20,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1604324241998-98d383867f37?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Exotic Farms',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 16,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '77',
    name: 'Fresh Kumquats',
    slug: 'fresh-kumquats',
    description: 'Sweet-tart kumquats. Unique citrus fruit eaten whole with the skin.',
    price: 5.99,
    discountPrice: 4.99,
    stock: 18,
    countInStock: 18,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1591335941363-fc9adb3d8ef5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Citrus Valley',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 14,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '78',
    name: 'Fresh Blackcurrants',
    slug: 'fresh-blackcurrants',
    description: 'Tart and flavorful blackcurrants. Great for jams, desserts, or eating fresh.',
    price: 5.49,
    discountPrice: 0,
    stock: 22,
    countInStock: 22,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1563746924237-f81657aaf8c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Berry Farms',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 15,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '79',
    name: 'Fresh Apricots',
    slug: 'fresh-apricots-organic',
    description: 'Sweet and tangy organic apricots. Perfect for snacking or baking.',
    price: 5.29,
    discountPrice: 4.49,
    stock: 25,
    countInStock: 25,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1599943503164-2dcaab73121a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Organic Farms',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 13,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '80',
    name: 'Fresh Nectarines',
    slug: 'fresh-nectarines',
    description: 'Juicy and sweet nectarines. Perfect for eating fresh or baking.',
    price: 4.99,
    discountPrice: 0,
    stock: 28,
    countInStock: 28,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1597393353083-05e159f2f1db?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Stone Fruit Farms',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 16,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '81',
    name: 'Fresh Plums',
    slug: 'fresh-plums-organic',
    description: 'Sweet and juicy organic plums. Freshly harvested and full of flavor.',
    price: 4.79,
    discountPrice: 3.99,
    stock: 30,
    countInStock: 30,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1599076996865-a98defbc9f23?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Organic Farms',
    rating: 4.4,
    averageRating: 4.4,
    numReviews: 12,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '82',
    name: 'Organic Dates',
    slug: 'organic-dates',
    description: 'Sweet and caramel-like organic dates. A natural energy booster.',
    price: 6.99,
    discountPrice: 0,
    stock: 25,
    countInStock: 25,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1613125700782-8394bec3b2ae?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Date Oasis',
    rating: 4.8,
    averageRating: 4.8,
    numReviews: 19,
    isFeatured: true,
    reviews: []
  }
];

export default lastFruits; 