// More vegetable products
const moreVegetables = [
  {
    _id: '53',
    name: 'Organic Mushrooms',
    slug: 'organic-mushrooms',
    description: 'Fresh organic mushrooms. Perfect for sautéing or adding to dishes.',
    price: 4.49,
    discountPrice: 3.99,
    stock: 35,
    countInStock: 35,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1576761702689-6542ce4583c2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Forest Fresh',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 15,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '54',
    name: 'Fresh Garlic',
    slug: 'fresh-garlic',
    description: 'Flavorful fresh garlic. Essential for many recipes.',
    price: 2.99,
    discountPrice: 0,
    stock: 45,
    countInStock: 45,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Garden Fresh',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 17,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '55',
    name: 'Green Cabbage',
    slug: 'green-cabbage',
    description: 'Fresh and crisp green cabbage. Great for slaws, stir-fries, or soups.',
    price: 3.29,
    discountPrice: 2.79,
    stock: 40,
    countInStock: 40,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1594282486552-05a6413eee3a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Farm Fresh',
    rating: 4.3,
    averageRating: 4.3,
    numReviews: 11,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '56',
    name: 'Fresh Cauliflower',
    slug: 'fresh-cauliflower',
    description: 'Fresh and nutritious cauliflower. Versatile for many dishes.',
    price: 3.79,
    discountPrice: 0,
    stock: 35,
    countInStock: 35,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1613743990305-d6bbf162d2fb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Green Valley',
    rating: 4.4,
    averageRating: 4.4,
    numReviews: 13,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '57',
    name: 'Eggplant',
    slug: 'eggplant',
    description: 'Fresh eggplant. Great for roasting, grilling, or making classic dishes.',
    price: 3.49,
    discountPrice: 2.99,
    stock: 30,
    countInStock: 30,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1596451190630-186aff535bf2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Fresh Fields',
    rating: 4.2,
    averageRating: 4.2,
    numReviews: 10,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '58',
    name: 'Fresh Ginger',
    slug: 'fresh-ginger',
    description: 'Aromatic fresh ginger. Essential for many cuisines and recipes.',
    price: 3.29,
    discountPrice: 0,
    stock: 38,
    countInStock: 38,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1603903823817-b941d76c7152?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Spice Farms',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 18,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '59',
    name: 'Fresh Corn',
    slug: 'fresh-corn',
    description: 'Sweet and juicy fresh corn. Perfect for grilling or boiling.',
    price: 3.99,
    discountPrice: 2.99,
    stock: 40,
    countInStock: 40,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1627228703184-e88890d2a592?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Farm Fresh',
    rating: 4.8,
    averageRating: 4.8,
    numReviews: 22,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '60',
    name: 'Fresh Celery',
    slug: 'fresh-celery',
    description: 'Crisp and fresh celery. Great for soups, salads, or snacking.',
    price: 2.79,
    discountPrice: 0,
    stock: 45,
    countInStock: 45,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1587049352851-8d4e89133924?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Garden Fresh',
    rating: 4.3,
    averageRating: 4.3,
    numReviews: 12,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '61',
    name: 'Green Beans',
    slug: 'green-beans',
    description: 'Fresh and tender green beans. Perfect for side dishes or casseroles.',
    price: 3.49,
    discountPrice: 2.99,
    stock: 38,
    countInStock: 38,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1567375698348-5d9d5ae99de0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Green Fields',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 14,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '62',
    name: 'Fresh Artichokes',
    slug: 'fresh-artichokes',
    description: 'Tender and delicious artichokes. Perfect for steaming or roasting.',
    price: 4.99,
    discountPrice: 0,
    stock: 25,
    countInStock: 25,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1620574387735-3624d75b2dbc?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Mediterranean Farms',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 16,
    isFeatured: true,
    reviews: []
  }
];

export default moreVegetables; 