// More fruit products
const moreFruits = [
  {
    _id: '43',
    name: 'Organic Grapefruit',
    slug: 'organic-grapefruit',
    description: 'Tangy and refreshing organic grapefruit. Great for juicing or eating fresh.',
    price: 4.29,
    discountPrice: 3.79,
    stock: 30,
    countInStock: 30,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1596273312170-8f231e21080b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Citrus Valley',
    rating: 4.3,
    averageRating: 4.3,
    numReviews: 11,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '44',
    name: 'Fresh Pomegranate',
    slug: 'fresh-pomegranate',
    description: 'Antioxidant-rich pomegranate. Sweet and tart, perfect for juicing or adding to salads.',
    price: 5.49,
    discountPrice: 0,
    stock: 25,
    countInStock: 25,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1541344999736-83eca272f6fc?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Exotic Fruits',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 17,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '45',
    name: 'Dragon Fruit',
    slug: 'dragon-fruit',
    description: 'Exotic dragon fruit with a mild sweet flavor. Beautiful and nutritious.',
    price: 6.99,
    discountPrice: 5.99,
    stock: 20,
    countInStock: 20,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1527325678457-068eabd8e229?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Exotic Farms',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 19,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '46',
    name: 'Fresh Lychee',
    slug: 'fresh-lychee',
    description: 'Sweet and fragrant lychee. A delicious exotic treat.',
    price: 7.99,
    discountPrice: 0,
    stock: 18,
    countInStock: 18,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1620981030995-d319b6d38494?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Exotic Fruits',
    rating: 4.8,
    averageRating: 4.8,
    numReviews: 16,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '47',
    name: 'Green Apples',
    slug: 'green-apples',
    description: 'Crisp and tart green apples. Perfect for eating fresh or baking.',
    price: 4.49,
    discountPrice: 3.99,
    stock: 35,
    countInStock: 35,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Local Orchards',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 14,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '48',
    name: 'Fresh Papaya',
    slug: 'fresh-papaya',
    description: 'Sweet and tropical papaya. Rich in enzymes and great for digestion.',
    price: 5.49,
    discountPrice: 0,
    stock: 22,
    countInStock: 22,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Tropical Farms',
    rating: 4.4,
    averageRating: 4.4,
    numReviews: 13,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '49',
    name: 'Passion Fruit',
    slug: 'passion-fruit',
    description: 'Tangy and aromatic passion fruit. Perfect for juices and desserts.',
    price: 6.49,
    discountPrice: 5.49,
    stock: 20,
    countInStock: 20,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1604495772376-9fbb3996c4f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Exotic Farms',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 15,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '50',
    name: 'Fresh Figs',
    slug: 'fresh-figs',
    description: 'Sweet and honeyed fresh figs. Perfect for desserts or pairing with cheese.',
    price: 7.49,
    discountPrice: 0,
    stock: 18,
    countInStock: 18,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1597095166794-36513dad77ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Mediterranean Farms',
    rating: 4.8,
    averageRating: 4.8,
    numReviews: 18,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '51',
    name: 'Fresh Coconut',
    slug: 'fresh-coconut',
    description: 'Tropical coconut with sweet water and meat. Fresh and nutritious.',
    price: 5.99,
    discountPrice: 4.99,
    stock: 25,
    countInStock: 25,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1581337299468-9d00a55ad756?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Tropical Delights',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 16,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '52',
    name: 'Star Fruit',
    slug: 'star-fruit',
    description: 'Crisp and mildly sweet star fruit. Creates beautiful star-shaped slices.',
    price: 5.79,
    discountPrice: 0,
    stock: 20,
    countInStock: 20,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1602488283247-29bf1f5b148a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Exotic Farms',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 12,
    isFeatured: false,
    reviews: []
  }
];

export default moreFruits; 