// More dairy products
const moreDairy = [
  {
    _id: '63',
    name: 'Mozzarella Cheese',
    slug: 'mozzarella-cheese',
    description: 'Fresh mozzarella cheese. Perfect for pizza, caprese salad, or melting.',
    price: 5.49,
    discountPrice: 4.99,
    stock: 35,
    countInStock: 35,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1589881133595-a3c085cb731d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Cheese Masters',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 19,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '64',
    name: 'Soy Milk',
    slug: 'soy-milk',
    description: 'Plant-based soy milk. Great alternative to dairy milk.',
    price: 3.99,
    discountPrice: 0,
    stock: 40,
    countInStock: 40,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Plant Milks',
    rating: 4.4,
    averageRating: 4.4,
    numReviews: 14,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '65',
    name: 'Blue Cheese',
    slug: 'blue-cheese',
    description: 'Tangy and savory blue cheese. Perfect for salads, burgers, or cheese boards.',
    price: 6.99,
    discountPrice: 5.99,
    stock: 25,
    countInStock: 25,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Cheese Masters',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 16,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '66',
    name: 'Half & Half Cream',
    slug: 'half-and-half-cream',
    description: 'Smooth and rich half & half cream. Perfect for coffee or cooking.',
    price: 3.79,
    discountPrice: 0,
    stock: 38,
    countInStock: 38,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1589985270994-b4eaa1ea1487?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Happy Cows',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 17,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '67',
    name: 'Blueberry Yogurt',
    slug: 'blueberry-yogurt',
    description: 'Creamy yogurt with real blueberries. A delicious and healthy treat.',
    price: 3.49,
    discountPrice: 2.99,
    stock: 40,
    countInStock: 40,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Dairy Delight',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 18,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '68',
    name: 'Parmesan Cheese',
    slug: 'parmesan-cheese',
    description: 'Aged Parmesan cheese. Perfect for grating over pasta or risotto.',
    price: 7.99,
    discountPrice: 0,
    stock: 30,
    countInStock: 30,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1528747045269-390fe33c19f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Cheese Masters',
    rating: 4.9,
    averageRating: 4.9,
    numReviews: 24,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '69',
    name: 'Whipping Cream',
    slug: 'whipping-cream',
    description: 'Rich whipping cream. Perfect for desserts and baking.',
    price: 4.49,
    discountPrice: 3.99,
    stock: 35,
    countInStock: 35,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1598559111706-54a5046d2ed3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Happy Cows',
    rating: 4.6,
    averageRating: 4.6,
    numReviews: 15,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '70',
    name: 'Low-Fat Milk',
    slug: 'low-fat-milk',
    description: 'Nutritious low-fat milk. Perfect for everyday use.',
    price: 3.49,
    discountPrice: 0,
    stock: 45,
    countInStock: 45,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Happy Cows',
    rating: 4.5,
    averageRating: 4.5,
    numReviews: 16,
    isFeatured: false,
    reviews: []
  },
  {
    _id: '71',
    name: 'Ricotta Cheese',
    slug: 'ricotta-cheese',
    description: 'Fresh ricotta cheese. Perfect for lasagna, cannoli, or spreading on toast.',
    price: 4.99,
    discountPrice: 4.49,
    stock: 32,
    countInStock: 32,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1551462048-8d933464049c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Cheese Masters',
    rating: 4.7,
    averageRating: 4.7,
    numReviews: 18,
    isFeatured: true,
    reviews: []
  },
  {
    _id: '72',
    name: 'Coconut Yogurt',
    slug: 'coconut-yogurt',
    description: 'Dairy-free coconut yogurt. Creamy and delicious plant-based alternative.',
    price: 4.99,
    discountPrice: 0,
    stock: 30,
    countInStock: 30,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    images: [],
    brand: 'Plant Milks',
    rating: 4.8,
    averageRating: 4.8,
    numReviews: 20,
    isFeatured: true,
    reviews: []
  }
];

export default moreDairy; 